version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  connect-to-aws:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout

      # - run:
      #     name: Inspect OIDC Token
      #     command: |
      #       echo "${CIRCLE_OIDC_TOKEN}" > token.jwt
      #       cat token.jwt | cut -d '.' -f2 | base64 -d | jq .

      - aws-cli/setup:
          role_arn: arn:aws:iam::124355672791:role/Testing
          profile_name: default
          region: us-east-1

      - run:
          name: Verify AWS Connection
          command: |
            aws sts get-caller-identity
            aws secretsmanager list-secrets --region us-east-1

workflows:
  version: 2
  test-aws-oidc:
    jobs:
      - connect-to-aws
