version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  inspect-oidc-token:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout

      - run:
          name: Inspect OIDC Token
          command: |
            echo "Decoding OIDC token..."
            echo "${CIRCLE_OIDC_TOKEN}" > token.jwt
            cat token.jwt | cut -d '.' -f2 | base64 -d | jq .

workflows:
  version: 2
  test-oidc-token:
    jobs:
      - inspect-oidc-token
