version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  connect-to-aws:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout

      - aws-cli/setup:
          role_arn: arn:aws:iam::124355672791:role/Testing
          profile_name: default
          region: us-east-1

      - run:
          name: Verify S3 Access
          command: |
            echo "Checking AWS identity..."
            aws sts get-caller-identity

            echo "Listing S3 buckets..."
            aws s3 ls

workflows:
  version: 2
  test-aws-s3-access:
    jobs:
      - connect-to-aws

