version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  connect-to-aws:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout

      - run:
          name: Print OIDC Token (Raw)
          command: |
            echo "OIDC Token:"
            echo "${CIRCLE_OIDC_TOKEN}"

      - aws-cli/setup:
          role_arn: arn:aws:iam::124355672791:role/Testing
          profile_name: default
          region: us-east-1
      - run:
          name: Verify AWS Connection
          command: |
            aws sts get-caller-identity
            aws secretsmanager list-secrets --region us-east-1

workflows:
  test-aws-oidc:
    jobs:
      - connect-to-aws
